<meta charset="utf-8">
<meta name="generator" content="atom">
<meta name="author" content="Giuseppe Naponiello">
<meta name="robots" content="INDEX,FOLLOW">
<meta name="copyright" content="&copy;2016 Arc-Team">
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=yes">
<meta name="description" content="">
<meta name="keywords"  content="">
<link rel="icon" href="../img/favicon.ico"/>
<link href="css/stile.css" rel="stylesheet" media="all" >
